# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/blocks/workflow.yml

run-tests:
  stage: test
  image: python:latest
  tags:
    - Linux
  interruptible: true
  before_script:
    - python3 --version  # For debugging
    - pip install virtualenv
    - mkdir /tmp/craft_test
    - cd /tmp/craft_test
    - virtualenv venv
    - source venv/bin/activate
    - pip install unittest-xml-reporting
  script:
    - cd /tmp/craft_test
    - craftBranch=master
    - echo "CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME"
    - |
      if [ "$CI_COMMIT_REF_NAME" = "dev" ]; then
        craftBranch=dev
      fi
    - echo "CI_MERGE_REQUEST_TARGET_BRANCH_NAME=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - |
      if [ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" = "dev" ]; then
        craftBranch=dev
      fi
    - echo "Going to checkout branch $craftBranch of craft-core"
    - git clone --depth 1 -b $craftBranch https://invent.kde.org/packaging/craft.git
    - mkdir blueprints
    - blueprintRoot=$(pwd)/blueprints/
    - "echo blueprintRoot: $blueprintRoot"
    - ln -s $CI_PROJECT_DIR $blueprintRoot/craft-blueprints-kde
    - python3 craft/bin/test/runtests.py --blueprint-root $blueprintRoot
  artifacts:
    reports:
      junit: JUnit*Results.xml
