# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/blocks/workflow.yml

run-tests:
  stage: test
  image: python:latest
  tags:
    - Linux
  interruptible: true
  before_script:
    - python3 --version  # For debugging
    - pip install virtualenv
    - mkdir /tmp/craft_test
    - cd /tmp/craft_test
    - virtualenv venv
    - source venv/bin/activate
    - pip install unittest-xml-reporting
  script:
    - cd /tmp/craft_test
    - craftBranch=master
    - echo "CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME"
    - |
      if [ "$CI_COMMIT_REF_NAME" = "dev" ]; then
        craftBranch=dev
      fi
    - echo "CI_MERGE_REQUEST_TARGET_BRANCH_NAME=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - |
      if [ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" = "dev" ]; then
        craftBranch=dev
      fi
    - echo "Going to checkout branch $craftBranch of craft-core"
    - git clone --depth 1 -b $craftBranch https://invent.kde.org/packaging/craft.git
    - mkdir blueprints
    - blueprintRoot=$(pwd)/blueprints/
    - "echo blueprintRoot: $blueprintRoot"
    - ln -s $CI_PROJECT_DIR $blueprintRoot/craft-blueprints-kde
    - python3 craft/bin/test/runtests.py --blueprint-root $blueprintRoot
  artifacts:
    reports:
      junit: JUnit*Results.xml

build-package-linux:
  # This job can be used to test the build of a package, e.g. when you update
  # the package to a new version. Set CRAFT_PACKAGE to the package you want to
  # test. This test uses the CI image that's also used for the AppImages.
  image: invent-registry.kde.org/sysadmin/ci-images/sles15-craft:latest
  rules:
    - when: manual
      # we don't want the manual job to block the pipeline
      allow_failure: true
  tags:
    - Linux
  variables:
    GIT_STRATEGY: none
    KDECI_CRAFT_PLATFORM: linux-64-gcc
    KDECI_CRAFT_CACHE: /mnt/craft-cache/$KDECI_CRAFT_PLATFORM/
    KDECI_CRAFT_CONFIG: ci-utilities/craft/qt6/CraftConfig.ini
    KDECI_CRAFT_PROJECT_CONFIG: $CI_PROJECT_DIR/.craft.ini
    CRAFT_PACKAGE:
  interruptible: true
  before_script:
    - if [ -z "$CRAFT_PACKAGE" ]; then echo "Error - Set CRAFT_PACKAGE to the package you want to test."; false; fi
    - export LANG=en_US.UTF-8
    - git clone https://invent.kde.org/packaging/craftmaster.git --branch=master
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1
    # Create empty .craft.ini if none exists
    - touch $KDECI_CRAFT_PROJECT_CONFIG
    # Define a short cut for the lengthy CraftMaster command line
    - function craftmaster { python3 craftmaster/CraftMaster.py --config $KDECI_CRAFT_CONFIG --config-override $KDECI_CRAFT_PROJECT_CONFIG --target $KDECI_CRAFT_PLATFORM $@; }
  script:
    # Set up craft settings and blueprint settings
    - craftmaster --setup
    # Get Craft itself ready
    - craftmaster -c -i --options virtual.ignored=True --update craft
    - craftmaster -c craft
    # Switch to this branch of craft-blueprints-kde
    - cd $CI_PROJECT_DIR/blueprints/craft-blueprints-kde
    - git checkout $CI_COMMIT_REF_NAME
    - cd $CI_PROJECT_DIR
    # Install all of our dependencies
    - craftmaster -c --install-deps $CRAFT_PACKAGE
    # Build the package
    - craftmaster -c --no-cache $CRAFT_PACKAGE
  artifacts:
    expire_in: 3 days
    when: always
    paths:
      - "$KDECI_CRAFT_PLATFORM/logs/"
