repos:
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
      args: ["--line-length", "160"]

-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
